# render.yaml
services:
  - type: web
    name: hackmatch-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: server.settings
      - key: SECRET_KEY
        value: 8867914141

