# Generated by Django 5.2.5 on 2025-08-13 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
        ('matcher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_role', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('other', 'Other')], max_length=20)),
                ('skills', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('shortlisted', 'Shortlisted'), ('matched', 'Matched'), ('withdrawn', 'Withdrawn')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='hackathons.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hackathon')},
            },
        ),
        migrations.DeleteModel(
            name='Hackathon',
        ),
    ]
